language: python

# command to run tests
install:
    - pip install coveralls
    - python setup.py develop
script:
    - coverage run --source=kdap -m unittest discover
after_success:
    - coveralls
